// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoprawaKolokwium.Models;

namespace PoprawaKolokwium.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PoprawaKolokwium.Models.Action", b =>
                {
                    b.Property<int>("IdAction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("NeedSpecialEquipment")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("IdAction");

                    b.ToTable("Actions");
                });

            modelBuilder.Entity("PoprawaKolokwium.Models.FireTruck", b =>
                {
                    b.Property<int>("IdFiretruck")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OperationalNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<bool>("SpecialEquipment")
                        .HasColumnType("bit");

                    b.HasKey("IdFiretruck");

                    b.ToTable("FireTrucks");
                });

            modelBuilder.Entity("PoprawaKolokwium.Models.Firefighter", b =>
                {
                    b.Property<int>("IdFirefighter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("IdFirefighter");

                    b.ToTable("Firefighters");
                });

            modelBuilder.Entity("PoprawaKolokwium.Models.Firefighter_Action", b =>
                {
                    b.Property<int>("IdFirefighter")
                        .HasColumnType("int");

                    b.Property<int>("IdAction")
                        .HasColumnType("int");

                    b.Property<int?>("ActionIdAction")
                        .HasColumnType("int");

                    b.Property<int?>("FirefighterIdFirefighter")
                        .HasColumnType("int");

                    b.HasKey("IdFirefighter", "IdAction");

                    b.HasIndex("ActionIdAction");

                    b.HasIndex("FirefighterIdFirefighter");

                    b.ToTable("Firefighter_Actions");
                });

            modelBuilder.Entity("PoprawaKolokwium.Models.Firetruck_Action", b =>
                {
                    b.Property<int>("IdAction")
                        .HasColumnType("int");

                    b.Property<int>("IdFiretruck")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssigmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdFiretruckAction")
                        .HasColumnType("int");

                    b.HasKey("IdAction", "IdFiretruck");

                    b.HasIndex("IdFiretruck");

                    b.ToTable("Firetruck_Actions");
                });

            modelBuilder.Entity("PoprawaKolokwium.Models.Firefighter_Action", b =>
                {
                    b.HasOne("PoprawaKolokwium.Models.Action", "Action")
                        .WithMany("Firefighter_Actions")
                        .HasForeignKey("ActionIdAction");

                    b.HasOne("PoprawaKolokwium.Models.Firefighter", "Firefighter")
                        .WithMany("Firefighter_Actions")
                        .HasForeignKey("FirefighterIdFirefighter");
                });

            modelBuilder.Entity("PoprawaKolokwium.Models.Firetruck_Action", b =>
                {
                    b.HasOne("PoprawaKolokwium.Models.Action", "Action")
                        .WithMany("Firetruck_Actions")
                        .HasForeignKey("IdAction")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoprawaKolokwium.Models.FireTruck", "FireTruck")
                        .WithMany("Firetruck_Actions")
                        .HasForeignKey("IdFiretruck")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
